### ISSUE TITLE
Add extra toEnglish transliterate/pronunciation keys

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/gurmukhi-utils#102]
Add BoS for now, will add others later.

**Comment by Sarabveer** [comment]
Some thoughts:
1. Should make BoS default or some other key from the Excel sheet default.
2. Remove current transliterations. They aren't as good compared to the other available ones that are in the file.

**Comment by bhajneet** [comment]
Required by ShabadOS/desktop#391
