### ISSUE TITLE
Add firstLetter for Translit/Pronunciations

### ISSUE THREAD

**Issue by Sarabveer** [ShabadOS/gurmukhi-utils#105]
Add option to get first letter of english transliteration. Allows for transliteration searching.

**Comment by bhajneet** [comment]
This is easy for now without multiple pronunciation sources. #102 may complicate it with multiple columns being required.

**Comment by bhajneet** [comment]
Also how do we handle first letters with more than one character? Some examples: ਖ as kh, ਭ as bh, ਥ as th

**Comment by bhajneet** [comment]
Depends on https://github.com/ShabadOS/desktop/issues/394

**Comment by Sarabveer** [comment]
This is for searching transliterations. Say someone was searching:
> tum daate tthaakur pratipaalak naaeik khasam hamaare |

I would be stored as `tdtpnkh`. This allows any spelling of the translit, as long as the first letter is correct.

**Comment by bhajneet** [comment]
> I would be stored as `tdtpnkh`. This allows any spelling of the translit, as long as the first letter is correct.

So you're suggesting prop 2, use first letters only.

For me, there is a bit of confusion on t vs tt vs tth of tthaakur. How does the user know what to type? How can we educate them to use only one letter? I think it would be safer to ask the user to type out the spaces and we strip the spaces and any non-first letter.

So continuing with prop 1 and 2 it would be:

`kh kh kh kh kh t n` => `kkkkktn` => `ਖਖਖਖਖਤਨ` and `ਕਕਕਕਕਤਨ` and every variation of k and kh between

`t d t p n k h` == `t d tth p n kh h` == `t d tt p n kh h` == `t d t p n kh hamaare`

This is more flexible imo for the user and encourages better interpretive search if we go to prop 3 in the future by allowing some extra chars to help refine the search queries.

**Comment by bhajneet** [comment]
I do like that using only the first letter like prop 2 acts almost exactly like first letters gurmukhi (without spaces) and lets the space char be used as a wildcard. So that's a big plus for prop 2 and not using spaces to separate chars.

**Comment by Sarabveer** [comment]
You are confusing me.

I search: `rakha ek hama swami`.

The search function would take the first letters, `rehs`, and then search that in the DB.

**Comment by bhajneet** [comment]
The discussion between desktop search and how gurmukhi-utils would store this in the db is about how the user searches pronunciations.

I think users would appreciate being able to search just first letters of english pronunciation. So if the line sung is rakha ek hamara swami, the user could input `rehs`, `r e h s`, etc. for first letter english pronunciation search.

This helps users that don't know which characters map ascii -> gurmukhi. Those users do know the sounds so they can search first letters with pronunciation chars.

I'm more and more leaning towards just using first letters only and hoping the user doesn't try to type in two or three chars for the same letter (tt / tth for ਠ). This would be prop 2 and allows the user to use wild cards. But comes at the cost of not allowing refined searches. So t will search ਤ ਥ ਟ ਠ and d will search ਦ ਧ ਡ ਢ. From my testing it's not too bad actually.

**Comment by Sarabveer** [comment]
This won't be just limited to desktop. Full translit search is needed for a website.

I guess first letter translit search is possible as well.

**Comment by bhajneet** [comment]
@saihaj can you implement prop 2 into gurmukhi-utils?

Each word should be converted to English pronunciation, then return the first letter of each word as a string

Example, passing `ਖੂਬੁ ਖੂਬੁ ਖੂਬੁ ਖੂਬੁ ਖੂਬੁ ਤੇਰੋ ਨਾਮੁ ॥` to function returns `kkkkktn` (via toEnglish.js pronunciation "khoob khoob khoob khoob khoob tero naam |")

**Comment by Harjot1Singh** [comment]
`firstLetters(toEnglish(input))` + some tests to verify input, add to a new file/function (need to think of name)

**Comment by bhajneet** [comment]
Include hindi/urdu

**Comment by saihaj** [comment]
I can do this
