### ISSUE TITLE
Transliteration corrections

### ISSUE THREAD

**Issue by preetcharan** [ShabadOS/gurmukhi-utils#123]
Referring to the pangti naanak kehat pukaar kai..., for three letter words that have 'haha' in the middle, the pronunciation rule is that the first letter gets a laav (if you're of that school of thought), so if possible can we develop the translit rules so it says 'kehat' not kahat. Similar word is like Sehaj.

In the next pangti sabh bheo paraaeo 

the rule does follow what i suggested but it's not needed, so if we could simplify to bheo and paraaeo that'd be ideal. 

![IMG_4193](https://user-images.githubusercontent.com/41019240/73656916-0bc2c880-4689-11ea-86b9-a897e4229401.jpg)
![IMG_1216](https://user-images.githubusercontent.com/41019240/73656918-0bc2c880-4689-11ea-97a5-0d979c829742.jpg)

**Comment by Sarabveer** [comment]
So, it would be transliterating ਕੇਹਤ and ਸੇਹਜ?

**Comment by bhajneet** [comment]
Using VS Code regex `.*gurmukhi.*[".,; ]([^iIuUyYwoOWmM",.; ][h][^iIuUyYwoOWmM",.; ])[\[".,; ].*` for 3 consonant-letter words with ਹ/haha as the center letter. (Not a perfect regex, so might have missed some instances). This gives 1.3k results across the database repo, half of them from Sri Guru Granth Sahib Ji. 

~90% of them are (per replacing XYZ in `.*gurmukhi.*(["\[.,; ]XYZ["\[.,; ]).*`):

Word | Count
|----|----|
ਸਹਜ | 370
ਰਹਤ | 217
ਕਹਤ | 215
ਪਹਰ | 157
ਸਹਸ | 90
ਮਹਲ | 52
ਟਹਲ | 32
ਕਹਨ | 17
ਕਹਣ | 5

Also, assuming @preetcharan meant dulaav not single laav, but to be translit as single laav perhaps to match common spellings?

So to give some examples (I don't have an opinion, just for illustration). 

Example Line | Source | Word | SoT | Translits
| ---- | ---- | ---- | ---- | ---- |
ਅਕਥ ਕਥਾ ਬਿਨੋਦ ਕਹਤ ਨ ਆਵਈ | Kabit Savaiye | ਕਹਤ | ਕੇਹਤ/ਕੈਹਤ | kahat vs kehat/kaihat
ਕਾਮ ਨਾਮ ਨਿਹਿਕਾਮ ਪਰਮਪਦ ਸਹਜ ਸਮਾਵੈ | Kabit Savaiye | ਸਹਜ | ਸੇਹਜ/ਸੈਹਜ  | sahaj vs sehaj/saihaj
ਘਟ ਘਟ ਕਾ ਪਰਵੇਸ ਸੇਸ ਪਹਿ ਕਹਤ ਨ ਆਵੈ | Kabit Savaiye | ਕਹਤ | ਕੇਹਤ/ਕੈਹਤ  | kahat vs kehat/kaihat
ਨਿਸ ਦਿਨ ਘਟਿਕਾ ਮਹੂਰਤ ਪਹਰ ਹੈ | Kabit Savaiye | ਪਹਰ | ਪੇਹਰ/ਪੈਹਰ  | pahar vs pehar/paihar
ਜਹਾਂ ਜਹਾਂ ਖ਼ਾਲਸਾ ਜੀ ਸਾਹਿਬ | Ardaas | ਜਹਾਂ | ਜੇਹਾਂ/ਜੈਹਾਂ  | jahan vs jehan/jaihan
ਤਹਾਂ ਤਹਾਂ ਰਛਿਆਂ ਰਿਆਇਤ | Ardaas | ਤਹਾਂ | ਤੇਹਾਂ/ਤੈਹਾਂ  | tahan vs tehan/taihan
ਜ਼ਿ ਫਜ਼ਲਿ ਅਹਦ ਰਹਿਮਤੁਲ ਮਜ਼ਨਬੀਨ | Ganj Nama | ਅਹਦ | ਅੇਹਦ/ਐਹਦ  | ahad vs aehad/aaihad
ਗੋਯਾਸਤ ਬਹਰ ਤਰਫ਼ ਸੁਰਾਗ਼ਤ ਜੋਯਾ | Guzals | ਬਹਰ | ਬੇਹਰ/ਬੈਹਰ  | bahar vs behar/baihar
ਰਿਆਜ਼ਿ ਜਿਨਾਂ ਰਾ ਨਸੀਮਿ ਸਹਰ | Jot Bigas | ਸਹਰ | ਸੇਹਰ/ਸੈਹਰ  | sahar vs sehar/saihar
ਅਧੋ ਮੁਖ, ਏਕ ਪਾਇ ਠਾਢੇ ਨ ਬਹਤ ਹੈਂ | Sri Dasam Granth | ਬਹਤ | ਬੇਹਤ/ਬੈਹਤ  | bahat vs behat/baihat
ਸਹਸ ਸਹਸ ਦਾਨਵ ਕਹ ਘਾਯੋ | Sri Dasam Granth | ਸਹਸ | ਸੇਹਸ/ਸੈਹਸ  | sahas vs sehas/saihas
ਸੁਖ਼ਨ ਰਾ ਬਹਕ ਜਾਇ ਸ਼ਰਫ਼ੋ ਦਿਹਦ | Sri Dasam Granth | ਬਹਕ | ਬੇਹਕ/ਬੈਹਕ  | bahak vs behak/baihak
ਕਰਉ ਬੇਨੰਤੀ, ਸੁਣਹੁ ਮੇਰੇ ਮੀਤਾ, ਸੰਤ ਟਹਲ ਕੀ ਬੇਲਾ | Sri Dasam Granth | ਟਹਲ | ਟੇਹਲ/ਟੈਹਲ  | tahal vs tehal/taihal
ਸਿਰੀਰਾਗੁ ਮਹਲ ੧ | Sri Guru Granth Sahib Ji | ਮਹਲ | ਮੇਹਲ/ਮੈਹਲ | mahal vs mehal/maihal

I heave heard dulaav being used for some of these pronunciations. I don't have an opinion on it.

At first glance, the single laav feels quite odd to me in pronunciation. What school of thought is this?

**Comment by Sarabveer** [comment]
Yes, single laav sounds odd? @preetcharan did you mean Dulavan?

**Comment by Sarabveer** [comment]
> ਸਿਰੀਰਾਗੁ ਮਹਲ ੧

@bhajneet In this case, it would be ਮਹੱਲ

**Comment by preetcharan** [comment]
@bhajneet @Sarabveer yes i'm really sorry i meant dulaav

**Comment by bhajneet** [comment]
> 
> 
> @bhajneet @Sarabveer yes i'm really sorry i meant dulaav

So did you want these to be `saihaj`, `raihat`, `kaihat`, ...? That is how dulaav is transliterated in other words according to BoS.

**Comment by preetcharan** [comment]
even though that's the rule, would actually prefer it as kehat, rehat, sehaj @bhajneet

**Comment by bhajneet** [comment]
@preetcharan Okay, we'll implement that.

@Sarabveer @Harjot1Singh note: these school of thought pronunciations relate to #102 and #124

**Comment by Sarabveer** [comment]
@bhajneet these aren't based on school of thought afaik, they should be just implemented.

**Comment by bhajneet** [comment]
Yeah, we can simply say this is the Basics of Sikhi pronunciation when we add options.
