### ISSUE TITLE
Add transliteration of yaiya variations

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/gurmukhi-utils#135]
@Sarabveer , @preetcharan, @sarigpani please come to a consensus for pronunciation

Need to add tests as well

**Comment by Sarabveer** [comment]
No one has proposed that it has anything different from the regular yaiyha, so it is just a stylistic variation.

It would also need to be added to the Unicode converter, where it would just convert to a regular yaiyha with the line on top

**Comment by Harjot1Singh** [comment]
Is this still in research, or ready to go?

**Comment by Sarabveer** [comment]
Will need to look at https://github.com/GurbaniNow/gurmukhi-fonts/issues/11
