### ISSUE TITLE
Add Pingal/Syllable Counter

### ISSUE THREAD

**Issue by Sarabveer** [ShabadOS/gurmukhi-utils#139]
This would be able give a count of syllables in a line for poetry.

All 35 Akhars including bindi chars count as 1 syllable.

There are 2 types of lagamatras, Harasv and Dheerag. Harasv doesn't count as a syllable, and Dheerag is 1 syllable.

Pairin Akhars also do not count as a syllable.

All other characters (such as Dandian) should be skipped.

**Comment by bhajneet** [comment]
Can you please provide a range of test lines and their count for testing?

**Comment by Sarabveer** [comment]
@bhajneet I was planning on doing that, it is required anyway

**Comment by HsinghN** [comment]
If we can have something like this, it will be very useful.

https://geet-gatiroop.manaskriti.com/
https://www.youtube.com/playlist?list=PLLrIxj3qOvhWLKcnueAGjm3gJhmz_EzC2
https://github.com/vanimurarka/rhythmin-verse

**Comment by HsinghN** [comment]
![page1](https://user-images.githubusercontent.com/26386021/83729099-85e07980-a68a-11ea-9d97-c5f76540b0b7.jpg)
![page2](https://user-images.githubusercontent.com/26386021/83729091-82e58900-a68a-11ea-8708-a6b0460f8e6c.jpg)
![page3](https://user-images.githubusercontent.com/26386021/83729095-8547e300-a68a-11ea-874c-a58686d7ff91.jpg)

**Comment by HsinghN** [comment]
ਆਦਿ ਗੁਰਏ ਨਮਹ ॥ --- 10
ਜੁਗਾਦਿ ਗੁਰਏ ਨਮਹ ॥ --- 11
ਸਤਿਗੁਰਏ ਨਮਹ ॥ --- 9
ਸ੍ਰੀ ਗੁਰਦੇਵਏ ਨਮਹ ॥੧॥ --- 12
ਦੀਨ ਦਰਦ ਦੁਖ ਭੰਜਨਾ ਘਟਿ ਘਟਿ ਨਾਥ ਅਨਾਥ ॥ --- 24
ਸਰਣਿ ਤੁਮੑਾਰੀ ਆਇਓ ਨਾਨਕ ਕੇ ਪ੍ਰਭ ਸਾਥ ॥੧॥ --- 22
ਬਹੁ ਸਾਸਤ੍ਰ ਬਹੁ ਸਿਮ੍ਰਿਤੀ ਪੇਖੇ ਸਰਬ ਢਢੋਲਿ ॥ --- 23
ਪੂਜਸਿ ਨਾਹੀ ਹਰਿ ਹਰੇ ਨਾਨਕ ਨਾਮ ਅਮੋਲ ॥੧॥ --- 23
ਨਿਰਗੁਨੀਆਰ ਇਆਨਿਆ ਸੋ ਪ੍ਰਭੁ ਸਦਾ ਸਮਾਲਿ ॥ --- 26
ਜਿਨਿ ਕੀਆ ਤਿਸੁ ਚੀਤਿ ਰਖੁ ਨਾਨਕ ਨਿਬਹੀ ਨਾਲਿ ॥੧॥ --- 24

**Comment by bhajneet** [comment]
Are there different schools of thought on counting? Is there a more preferred/popular/common rule set compared to others? Just wondering

**Comment by Sarabveer** [comment]
> 
> 
> Are there different schools of thought on counting? Is there a more preferred/popular/common rule set compared to others? Just wondering

I am not aware of different schools of thought on counting.

**Comment by Sarabveer** [comment]
![image](https://user-images.githubusercontent.com/4297171/96280305-cf7c9180-0fa5-11eb-9836-69cfef8a25cc.png)
