### ISSUE TITLE
Find Unicode Gurmukhi instead of ASCII in Search query in Lines Model

### ISSUE THREAD

**Issue by Sarabveer** [ShabadOS/gurmukhi-utils#140]
Currently, `is-ascii` is being used to detect if the search query is in the GurbaniAkhar format. 

However, GurbaniAkhar has letters that are outside the 128char ASCII range. This triggers the search to convert Unicode -> GurbaniAkhar, which messes up the search query (esp in Full Word searches).

Solutions:

1. Find a library that can check if a character is in a unicode block

2. Build own solution in `gurmukhi-utils` to check if string has Unicode Gurmukhi

**Comment by bhajneet** [comment]
@Harjot1Singh How best to add a single line func like this?

**Comment by bhajneet** [comment]
Required for https://github.com/ShabadOS/desktop/pull/543 refactor and https://github.com/ShabadOS/database/blob/dev/lib/models/Lines.js#L39

**Comment by Harjot1Singh** [comment]
Waiting on https://github.com/ShabadOS/gurmukhi-utils/pull/141

**Comment by bhajneet** [comment]
Perhaps this issue should be broken, as the PR is set to close this one.

**Comment by bhajneet** [comment]
Whoever is assigned to this needs to finish it ASAP if we are to release Desktop on Monday, June 1st
