### ISSUE TITLE
Confirm first letter shahmukhi for search input

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/gurmukhi-utils#153]
Don't want to block #152, and I'm sure testing is a long process. See firstLetters function for shahmukhi strings.

_Originally posted by @bhajneet in https://github.com/ShabadOS/gurmukhi-utils/pull/152_

**Comment by Sarabveer** [comment]
I wouldn't include shahmukhi in anything at the moment.

**Comment by bhajneet** [comment]
Out of scope until shahmukhi knowledge base is improved to provide support
