### ISSUE TITLE
Rename stripAccents to something more familiar?

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/gurmukhi-utils#165]
I suggested "toBaseForm" or "toCoreConsonant" or such. However, Harjot pointed out that there is a convention to use "strip". 

I wonder if we can simply use the same function as the "main letters" column? They would be to base character since we only use main letters for search purposes? 

_Originally posted by @bhajneet in https://github.com/ShabadOS/desktop/pull/579/files/610320d6eeeb02bfc8d5a57cd320ef1d1042dc42_

---

Bhajneet those are mostly vowels, with the exception of the last 3/4. We can certainly look at renaming the function, but please FAI in gurmukhi-utils.

One preliminary note is that our convention so far has been to name anything that removes something to `stripSomething`, instead of `toSomethingElse`, so I'd recommend us trying to be consistent about it

_Originally posted by @Harjot1Singh in https://github.com/ShabadOS/desktop/pull/579/files/610320d6eeeb02bfc8d5a57cd320ef1d1042dc42_

**Comment by bhajneet** [comment]
The first table of akhars are what we are trying to pull from the data afaik: https://en.wikipedia.org/wiki/Gurmukhi#Alphabet

**Comment by Sarabveer** [comment]
`toBaseForm` sounds appropriate.
