### ISSUE TITLE
Transliteration error

### ISSUE THREAD

**Issue by preetcharan** [shabados/gurmukhi-utils#185]
On the transliteration for 'pair' letter ShabadOS is producing the @ sign.

See image below:
<img width="2228" alt="image" src="https://user-images.githubusercontent.com/41019240/103340665-8ef8c400-4a7c-11eb-8a5e-92b579ce3541.png">

Letter should be ignored in the transliteration

Mac OS Mojave
iMac 
Shabad OS App Version 2.9.0, Database Version 4.7.0

**Comment by bhajneet** [comment]
@Harjot1Singh adding this works:

![image](https://user-images.githubusercontent.com/14130567/103356408-d6804f80-4a7e-11eb-9392-c01b398f373c.png)

What's currently in place doesn't work idk why:
 
![image](https://user-images.githubusercontent.com/14130567/103356433-e6982f00-4a7e-11eb-8a20-ac09b8ec4dd4.png)

![image](https://user-images.githubusercontent.com/14130567/103356474-f879d200-4a7e-11eb-9201-259e5ee3af0f.png)

**Comment by Harjot1Singh** [comment]
Could you check if passing any other character in the `supressions` list causes it to be displayed? Perhaps we should write a test case for this.

**Comment by bhajneet** [comment]
Yeah I was just investigating that. None of the suppressions were actually being suppressed. I added two test cases, will sort it out.

**Comment by bhajneet** [comment]
Very confused

![image](https://user-images.githubusercontent.com/14130567/103362053-5dd1c100-4a87-11eb-8131-0d2171ddbdbb.png)

Transliteration map seems correct per first parameter of console log. Transliteration doesn't suppress per second and third parameters of console log. Transliteration works if adding line 195.

Going to unassign myself

**Comment by Harjot1Singh** [comment]
I see! It's because of the passthrough: `transliterationMap[ '@' ] === '' == false`, therefore the `|| letter` kicks in. Did you push the test cases up anywhere?

**Comment by bhajneet** [comment]
I didn't push, but I just added the OP word and khanda symbol as two tests
