### ISSUE TITLE
toAscii for non gurbani text

### ISSUE THREAD

**Issue by sanbroz** [shabados/gurmukhi-utils#196]
Hi, Can we use toAscii and other translation function with general Punjabi text other then Gurbani text?

**Comment by Harjot1Singh** [comment]
Hi there!

Yes - it should work.

Out of interest, what is your use case?

**Comment by bhajneet** [comment]
Hi,

There is a website https://unicode.sarabveer.me/ that I believe uses gurmukhi-utils on the backend. It should give you an idea of what is possible.

If you run into any issues, please let us know or open a PR to this repo to fix it. I'm also interested how you're planning to use gurmukhi-utils, please let us know when you get a chance!

**Comment by sanbroz** [comment]
Thanks, I just wanted to build a cli tool to convert text files to and from
Unicode text.

Thanks for your help

**Comment by bhajneet** [comment]
Imo, this example `ibMRdwbn` is incorrectly written in ASCII. It should be `ibRMdwbn` which does correctly translate to ਬ੍ਰਿੰਦਾਬਨ. Perhaps a pre-processing step that finds `MR` and swaps them to `RM` would be the solution?

**Comment by Sarabveer** [comment]
`ibRMdwbn` is correct. Pronunciation goes: `ਬ੍ਰ` + `ਿ` + `ੰ` + `ਦਾ` + `ਬਨ`

ਬ੍ਰਿੰਦਾਬਨ = ਬ `U+0A2C` +  ੍ `U+0A4D` + ਰ `U+0A30` + ਿ `U+0A3F` + ੰ `U+0A70` + ਦ `U+0A26` + ਾ `U+0A3E` + ਬ `U+0A2C` + ਨ `U+0A28`

I am not sure about swapping `MR` and `RM`, might introduce edge cases.
