### ISSUE TITLE
stripEndings removing number from translation

### ISSUE THREAD

**Issue by sarabveer** [ShabadOS/gurmukhi-utils#197]
https://github.com/shabados/gurmukhi-utils/blob/2d193029dac68408fb659231ea523d683e582ac9/test/stripEndings.spec.js#L48

**Comment by Sarabveer** [comment]
Similar situation here, 1753 is part of the translation

https://github.com/shabados/gurmukhi-utils/blob/2d193029dac68408fb659231ea523d683e582ac9/test/stripEndings.spec.js#L103

**Comment by bhajneet** [comment]
As indicated by the comment/documentation:

Not designed for headings or Sirlekhs.

**Comment by bhajneet** [comment]
I didn't see the second comment. Re-opening as an issue and renaming title.

**Comment by InderdeepBajwa** [comment]
This is caused by: https://github.com/shabados/gurmukhi-utils/blob/bd76ea455f50af141593396b1f0b6c2ab24bd9d3/lib/stripEndings.js#L31

**Comment by bhajneet** [comment]
This is fixed in python. The following tests pass.

```

    {
      "name": "remove line endings - negative",
      "functions": ["rle"],
      "type": "is",
      "assertions": {
        "ਮਹਲਾ ੧": "ਮਹਲਾ ੧",
        "ਮਹਲਾ ੫": "ਮਹਲਾ ੫",
        "mahalaa 1": "mahalaa 1",
        "महला ५": "महला ५",
        "It was Bikrami Samvat 1753": "It was Bikrami Samvat 1753"
      }
    }
```
