### ISSUE TITLE
"firsLetters" function is not aligned with 'first_letters' colum of 'line' table from ShabadOs database

### ISSUE THREAD

**Issue by RamnSingh** [shabados/gurmukhi-utils#199]
### Question

I am trying to query data from 'lines' table of ShabadOs database using 'first_letters'  column. Before I fetch data, for some reasons I use firstLetters function from 'gurmukhi-utils' on a line from ShabadOs database. I found out that in the column 'first_letters' of 'lines' table of the database is ignoring lower case 'i' therefore there is no lower case 'i' in the 'first_letters' column for any row in the database but the firstLetters function is not ignoring the lower case 'i'. Is it intentional this behavior ?

Example from a line taken from ShabadOs database: 

 **id             shabad_id     first_letters     gurmukhi
"C5NR"	"ZKH"            "gkvvv"	  "gwvY ko; ividAw ivKmu vIcwru ]"**

As you can see the column 'first_letters' for the data from 'gurmukhi' column is 'gkvvv' and apparently it is skipping every lower case 'i' but on the hand when i run 'firstLetters' function from 'gurmukhi-utils' it is not skipping lower case 'i'.

firstLetters("gwvY ko; ividAw ivKmu vIcwru ]"); // it gives me "gkiiv".

I just want to know is it intentional or it is a bug ?

Dhanwaad

**Comment by bhajneet** [comment]
Hello,

If you take the `gurmukhi` string `gwvY ko; ividAw ivKmu vIcwru ]` and convert it into unicode / transliterate to English, you will get:

> ਗਾਵੈ ਕੋ; ਵਿਦਿਆ ਵਿਖਮੁ ਵੀਚਾਰੁ ॥

> gaavai ko; vidiaa vikham veechaar |

As you can see, the first letters are `gkvvv`. The lower case `i` in the old ASCII gurbani fonts is the equivalent of unicode `ਿ` as you can see on the first 2 v-starting words.

If you read the docs for `firstLetters` you will see that it is intended to run on unicode gurmukhi/hindi or english transliterations:

> Generates the first letters for a unicode Gurmukhi, Hindi transliteration, or English transliteration string. Includes any end-word vishraams, and line-end characters.

It is not meant to be used on the ASCII gurbani font language. So I can confirm that you would get `gkiiv` using firstLetters on the string `gwvY ko; ividAw ivKmu vIcwru ]`, but that is not something we intended firstLetters to be used on. Perhaps you can convert to unicode before running firstLetters then converting back to ASCII?

Or I suppose, may I ask what you're trying to accomplish? Then maybe we can help better.

**Comment by RamnSingh** [comment]
Thank you for clarifying about 'firstLetters' function. I will be first converting the text to Unicode then to ASCII as you suggested.

I would try to connect with you and other members of ShabadOS team on slack to further share informations about what I am building.

Thank you once again.
