### ISSUE TITLE
Remove Rahao from First Letters

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/gurmukhi-utils#25]
`app` should show up higher in search results but the "rahao" in the line fails search priority

**Comment by Harjot1Singh** [comment]
Any ideas on consistent detection? Could someone add in some failing tests

**Comment by bhajneet** [comment]
https://github.com/ShabadOS/desktop/issues/46

**Comment by Harjot1Singh** [comment]
Need more insight. What happens when we have lines which have a break inbetween/rahao, but then another line? I think we have some instances of that in our DB.

**Comment by bhajneet** [comment]
I hope there are 0 instances of that. I can't think of any scenario requiring a rahao line-ending in the middle of a line.

Can you run some query to check?

**Comment by Harjot1Singh** [comment]
@bhajneet Does this apply to things like `] 3 ]` etc?

Could you and @Sarabveer provide me with any conditions beyond matching `rhwao`?

**Comment by bhajneet** [comment]
The number should never be conflicting with matches. That is a separate requirement. `jkmjmk` should be an exact match for `jy ko mMin jwxY; min koie ]12]`.

Use regex search in VS Code `"SGPC": ".* \].* .* .* \]"`.  For SGGS ji this should suffice: `rhwau, Cky, Ckw`.

Exact match query | For line | In Unicode
|---|---|---|
sGrvq | so Gru rwKu; vfweI qoie ]1] rhwau ] | ਸੋ ਘਰੁ ਰਾਖੁ; ਵਡਾਈ ਤੋਇ ॥੧॥ ਰਹਾਉ ॥
hpqKm | hukmu pCwix; qw KsmY imlxw ]1] rhwau dUjw ] | ਹੁਕਮੁ ਪਛਾਣਿ; ਤਾ ਖਸਮੈ ਮਿਲਣਾ ॥੧॥ ਰਹਾਉ ਦੂਜਾ ॥
ann -OR- Enn -OR- Apslr | Ehu. nyhu nvylw ] Apuny pRIqm isau; lwig rhY ]1] rhwau ] | ਓਹੁ. ਨੇਹੁ ਨਵੇਲਾ ॥ ਅਪੁਨੇ ਪ੍ਰੀਤਮ ਸਿਉ; ਲਾਗਿ ਰਹੈ ॥੧॥ ਰਹਾਉ ॥
nAdnkAsG | nwmu ADwru dIjY. nwnk kau; Awnd sUK GnyrY ]2]12] Cky 2 ] | ਨਾਮੁ ਅਧਾਰੁ ਦੀਜੈ. ਨਾਨਕ ਕਉ; ਆਨਦ ਸੂਖ ਘਨੇਰੈ ॥੨॥੧੨॥ ਛਕੇ ੨ ॥
jjnjqbndb | jip jip nwmu jIvw qyrI bwxI; nwnk dws bilhwry ]2]18] Cky 3 ] | ਜਪਿ ਜਪਿ ਨਾਮੁ ਜੀਵਾ ਤੇਰੀ ਬਾਣੀ; ਨਾਨਕ ਦਾਸ ਬਲਿਹਾਰੇ ॥੨॥੧੮॥ ਛਕੇ ੩ ॥
ssnmmjjngjr | shs isAwxp nh imlY, myrI ijMduVIey; jn nwnk. gurmuiK jwqw rwm ]4]6] Ckw 1 ] | ਸਹਸ ਸਿਆਣਪ ਨਹ ਮਿਲੈ, ਮੇਰੀ ਜਿੰਦੁੜੀਏ; ਜਨ ਨਾਨਕ. ਗੁਰਮੁਖਿ ਜਾਤਾ ਰਾਮ ॥੪॥੬॥ ਛਕਾ ੧ ॥

@Sarabveer Is there an issue open to remove any lines having multiple line endings? Like ਓਹੁ ਨੇਹੁ ਨਵੇਲਾ example above

**Comment by Harjot1Singh** [comment]
Expose `stripRahao` publicly, or keep it internal to first letter? I suspect we're gonna want this with our new full word searching column, no?

**Comment by Harjot1Singh** [comment]
FYI anything with multiple line endings is going to be tricky to deal with - I recommend just deferring the correct matching behaviour to splitting the lines correctly in DB.

**Comment by bhajneet** [comment]
I believe you will need this for full word exact match

**Comment by bhajneet** [comment]
Some additional examples:

Line | In Unicode
|---|---|
Awie imlu gurisK. Awie imlu; qU myry gurU ky ipAwry ] rhwau ] | ਆਇ ਮਿਲੁ ਗੁਰਸਿਖ. ਆਇ ਮਿਲੁ; ਤੂ ਮੇਰੇ ਗੁਰੂ ਕੇ ਪਿਆਰੇ ॥ ਰਹਾਉ ॥
jhw qy aupijAw; iPir qhw smwvY [49[1[ ieku [ | ਜਹਾ ਤੇ ਉਪਜਿਆ; ਫਿਰਿ ਤਹਾ ਸਮਾਵੈ ।੪੯।੧। ਇਕੁ ।
nwnk scu swlwih; pUrw pwieAw ]27] suDu | ਨਾਨਕ ਸਚੁ ਸਾਲਾਹਿ; ਪੂਰਾ ਪਾਇਆ ॥੨੭॥ ਸੁਧੁ
nwnk. min qin cwau eyhu; inq pRB kau loVy ]21]1] suDu kIcy | ਨਾਨਕ. ਮਨਿ ਤਨਿ ਚਾਉ ਏਹੁ; ਨਿਤ ਪ੍ਰਭ ਕਉ ਲੋੜੇ ॥੨੧॥੧॥ ਸੁਧੁ ਕੀਚੇ
iesu bMdy isir julmu hoq hY; jmu. nhI htY gusweI ]4]9] duquky | ਇਸੁ ਬੰਦੇ ਸਿਰਿ ਜੁਲਮੁ ਹੋਤ ਹੈ; ਜਮੁ. ਨਹੀ ਹਟੈ ਗੁਸਾਈ ॥੪॥੯॥ ਦੁਤੁਕੇ

TTR +45 min

**Comment by Harjot1Singh** [comment]
Gone over the cases. Do we think a regex like `[॥\|।\]\[].*[॥\|।\]\[]` (match between line ending chars) would be suitable for 90% of the cases here?

We could even match on `[॥\|।\]\[].*`, so that all the chars onwards from a line ending char will be matched, which would give us 100% coverage over the lines you've provided, however I'm unsure if this will be problematic (should we have ANY lines in our DB joined together by a line ending?)
